DROP TABLE IF EXISTS BUYER_USER;
CREATE TABLE BUYER_USER
(
    USER_ID         BIGINT      NOT NULL COMMENT '用户ID',
    USER_NAME       VARCHAR(90) NOT NULL COMMENT '用户名称',
    NICK_NAME       VARCHAR(90) COMMENT '用户昵称',
    USER_INTRO      VARCHAR(300) COMMENT '个性签名',
    AVATAR          VARCHAR(1000) COMMENT '头像图片',
    EMAIL           VARCHAR(60) COMMENT '邮件地址',
    PHONE           VARCHAR(60) COMMENT '手机号',
    USER_PASS       VARCHAR(60) COMMENT '密码',
    PASS_SALT       VARCHAR(60) COMMENT '密码盐',
    USER_STATUS     VARCHAR(32) DEFAULT '1' COMMENT '用户状态',
    USER_SCORE      INT COMMENT '用户打分',
    TOTAL_COST_AMT  DECIMAL(24, 6) COMMENT '累计消费金额',
    LAST_LOGIN_TIME DATETIME COMMENT '最后登录时间',
    CREATED_BY      VARCHAR(32) COMMENT '创建人',
    CREATED_TIME    DATETIME COMMENT '创建时间',
    UPDATED_BY      VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME    DATETIME COMMENT '更新时间',
    PRIMARY KEY (USER_ID)
) COMMENT = '买家';

DROP TABLE IF EXISTS BUYER_ORDER;
CREATE TABLE BUYER_ORDER
(
    ORDER_ID       BIGINT NOT NULL COMMENT '订单ID',
    USER_ID        BIGINT NOT NULL COMMENT '用户ID',
    ADDRESS_ID     BIGINT COMMENT '地址ID',
    COUPON_ID      VARCHAR(50) COMMENT '优惠券ID',
    TOTAL_PRICE    DECIMAL(24, 6) COMMENT '总金额',
    COUPON_PRICE   DECIMAL(24, 6) COMMENT '优惠金额',
    PAYABLE_PRICE  DECIMAL(24, 6) COMMENT '应付金额',
    PAY_METHOD     VARCHAR(32) COMMENT '支付方式',
    INVOICE_TPL_ID VARCHAR(32) COMMENT '开票设置ID',
    LEAVE_COMMENT  VARCHAR(1000) COMMENT '订单留言备注',
    ORDER_STATUS   VARCHAR(32) COMMENT '订单状态',
    CREATED_BY     VARCHAR(32) COMMENT '创建人',
    CREATED_TIME   DATETIME COMMENT '创建时间',
    UPDATED_BY     VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME   DATETIME COMMENT '更新时间',
    PRIMARY KEY (ORDER_ID)
) COMMENT = '订单';

DROP TABLE IF EXISTS BUYER_ITEM;
CREATE TABLE BUYER_ITEM
(
    ORDER_ID     BIGINT      NOT NULL COMMENT '订单ID',
    ITEM_ID      VARCHAR(32) NOT NULL COMMENT '明细项ID',
    SKU_ID       BIGINT COMMENT '商品ID',
    SKU_TITLE    VARCHAR(90) COMMENT '商品标题',
    SKU_INTRO    VARCHAR(3000) COMMENT '商品介绍',
    PRICE        DECIMAL(24, 6) COMMENT '原价',
    SALE_PRICE   DECIMAL(24, 6) COMMENT '售价',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (ORDER_ID, ITEM_ID)
) COMMENT = '购买明细';

DROP TABLE IF EXISTS BUYER_ADDRESS;
CREATE TABLE BUYER_ADDRESS
(
    ADDRESS_ID   BIGINT NOT NULL COMMENT '地址ID',
    ADDRESS_NAME VARCHAR(60) COMMENT '地址名称',
    SEQ_NUMBER   INT COMMENT '顺序号',
    PROVINCE     VARCHAR(60) COMMENT '省',
    CITY         VARCHAR(60) COMMENT '市',
    COUNTY       VARCHAR(60) COMMENT '区',
    STREET       VARCHAR(60) COMMENT '街道',
    LAST_DETAIL  VARCHAR(60) COMMENT '门牌号',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (ADDRESS_ID)
) COMMENT = '地址';

DROP TABLE IF EXISTS SELLER_STOCK;
CREATE TABLE SELLER_STOCK
(
    SKU_ID        BIGINT       NOT NULL COMMENT '商品SKU',
    GOODS_ID      BIGINT       NOT NULL COMMENT '商品编号',
    SKU_NAME      VARCHAR(900) NOT NULL COMMENT 'SKU名称',
    PRICE         DECIMAL(24, 6) COMMENT '价格',
    PROMOTE_PRICE DECIMAL(24, 6) COMMENT '促销价格',
    COST_PRICE    DECIMAL(24, 6) COMMENT '成本价',
    STOCK         INT COMMENT '库存',
    PICTURE       VARCHAR(90) COMMENT 'SKU图片',
    QRCODE        VARCHAR(90) COMMENT '二维码',
    WEIGHT        DECIMAL(24, 6) COMMENT '重量',
    VOLUME        DECIMAL(24, 6) COMMENT '体积',
    REVISION      VARCHAR(32) COMMENT 'REVISION',
    CREATED_BY    VARCHAR(32) COMMENT 'CREATED_BY',
    CREATED_TIME  DATETIME COMMENT 'CREATED_TIME',
    UPDATED_BY    VARCHAR(32) COMMENT 'UPDATED_BY',
    UPDATED_TIME  DATETIME COMMENT 'UPDATED_TIME',
    PRIMARY KEY (SKU_ID)
) COMMENT = '库存';

DROP TABLE IF EXISTS SELLER_GOODS;
CREATE TABLE SELLER_GOODS
(
    GOODS_ID          BIGINT      NOT NULL COMMENT '商品ID',
    GOODS_NAME        VARCHAR(90) NOT NULL COMMENT '商品名称',
    CATEGORY_ID       INT COMMENT '商品分类',
    GOODS_TYPE        VARCHAR(2) COMMENT '商品类型',
    PRICE             DECIMAL(24, 6) COMMENT '原价格',
    PROMOTE_PRICE     DECIMAL(24, 6) COMMENT '促销价格',
    COST_PRICE        DECIMAL(24, 6) COMMENT '成本价格',
    SHIPPING_FEE      DECIMAL(24, 6) COMMENT '运费',
    MAX_BUY           INT COMMENT '限购数量',
    CLICKS            INT COMMENT '点击量',
    SALES             INT COMMENT '销售量',
    COLLECTS          INT COMMENT '收藏量',
    PICTURE           VARCHAR(60) COMMENT '商品图片',
    INTRODUCTION      VARCHAR(900) COMMENT '商品简介',
    DESCRIPTION       VARCHAR(900) COMMENT '商品描述',
    QRCODE            VARCHAR(90) COMMENT '商品二维码',
    STATE             VARCHAR(2) COMMENT '商品状态',
    SORT              INT COMMENT '排序号',
    GOODS_SPEC_FORMAT VARCHAR(900) COMMENT '商品规格',
    GOODS_WEIGHT      DECIMAL(24, 6) COMMENT '商品重量',
    GOODS_VOLUME      DECIMAL(24, 6) COMMENT '商品体积',
    CREATED_BY        VARCHAR(32) COMMENT 'CREATED_BY',
    CREATED_TIME      DATETIME COMMENT 'CREATED_TIME',
    UPDATED_BY        VARCHAR(32) COMMENT 'UPDATED_BY',
    UPDATED_TIME      DATETIME COMMENT 'UPDATED_TIME',
    PRIMARY KEY (GOODS_ID)
) COMMENT = '商品';

